### ISSUE TITLE
Module "eslint-plugin-format" has no exported member 'default'.

### ISSUE THREAD

**Issue by sao-coding** [antfu/eslint-plugin-format#11]
### Describe the bug

eslint-plugin-format v1.1.0

Module "eslint-plugin-format" has no exported member 'default'.

<img width="1372" height="392" alt="Image" src="https://github.com/user-attachments/assets/41f3bbc8-1e90-4d0f-b9cc-4a33f9ceaee4" />

<img width="3732" height="1258" alt="Image" src="https://github.com/user-attachments/assets/e6e368dc-4177-44fd-af35-554695d92c42" />

### Reproduction

export { default as formatPlugin } from 'eslint-plugin-format'

### System Info

```Shell
System:
    OS: Windows 11 10.0.26200
    CPU: (24) x64 AMD Ryzen 9 9900X 12-Core Processor
    Memory: 9.92 GB / 31.16 GB
  Binaries:
    Node: 24.11.1 - D:\Programs\nodejs\node.EXE
    npm: 11.6.2 - D:\Programs\nodejs\npm.CMD
    pnpm: 10.11.0 - D:\Programs\pnpm\pnpm.CMD
    bun: 1.3.3 - D:\Programs\pnpm\bun.CMD
  Browsers:
    Edge: Chromium (142.0.3595.94)
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Should be fixed in the latest version. Can you check again? Thanks

**Comment by sao-coding** [comment]
@antfu I’ve checked again on the latest version, but the issue still persists and hasn’t been fixed.
<img width="1154" height="1242" alt="Image" src="https://github.com/user-attachments/assets/9f2a59a2-63fe-47d3-b646-377f3c7700cd" />

**Comment by dartess** [comment]
v1.3.1, still get `has no default export.`
